# Generated by Django 4.2.7 on 2023-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet_id', models.AutoField(primary_key=True, serialize=False)),
                ('planet_title', models.CharField(blank=True, max_length=200, null=True)),
                ('planet_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('planet_image', models.ImageField(blank=True, null=True, upload_to='planet')),
            ],
        ),
    ]
